// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef UI_COMPASSSCREEN_H
#define UI_COMPASSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CompassScreen
extern void ui_CompassScreen_screen_init(void);
extern void ui_CompassScreen_screen_destroy(void);
extern lv_obj_t * ui_CompassScreen;
extern lv_obj_t * ui_CompassTitleLabel;
extern lv_obj_t * ui_CompassStatusLabel;
extern lv_obj_t * ui_CompassDirectionLabel;
extern lv_obj_t * ui_CompassHeadingLabel;
extern lv_obj_t * ui_CompassPitchLabel;
extern lv_obj_t * ui_CompassRollLabel;
extern void ui_event_CompassBackButton(lv_event_t * e);
extern lv_obj_t * ui_CompassBackButton;
extern lv_obj_t * ui_EnvBackLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

