// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_CompassScreen = NULL;
lv_obj_t * ui_CompassTitleLabel = NULL;
lv_obj_t * ui_CompassStatusLabel = NULL;
lv_obj_t * ui_CompassDirectionLabel = NULL;
lv_obj_t * ui_CompassHeadingLabel = NULL;
lv_obj_t * ui_CompassPitchLabel = NULL;
lv_obj_t * ui_CompassRollLabel = NULL;
lv_obj_t * ui_CompassBackButton = NULL;
lv_obj_t * ui_EnvBackLabel2 = NULL;
// event funtions
void ui_event_CompassBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_CompassScreen_screen_init(void)
{
    ui_CompassScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CompassScreen, lv_color_hex(0xF4F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassTitleLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassTitleLabel, 0);
    lv_obj_set_y(ui_CompassTitleLabel, 10);
    lv_obj_set_align(ui_CompassTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CompassTitleLabel, "COMPASS");
    lv_obj_set_style_text_font(ui_CompassTitleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassStatusLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassStatusLabel, 0);
    lv_obj_set_y(ui_CompassStatusLabel, 42);
    lv_obj_set_align(ui_CompassStatusLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CompassStatusLabel, "CALIBRATING");
    lv_obj_set_style_text_color(ui_CompassStatusLabel, lv_color_hex(0xFFA540), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompassStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassDirectionLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassDirectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassDirectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassDirectionLabel, -2);
    lv_obj_set_y(ui_CompassDirectionLabel, -51);
    lv_obj_set_align(ui_CompassDirectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassDirectionLabel, "--");
    lv_obj_set_style_text_font(ui_CompassDirectionLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassHeadingLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassHeadingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassHeadingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassHeadingLabel, 2);
    lv_obj_set_y(ui_CompassHeadingLabel, -19);
    lv_obj_set_align(ui_CompassHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassHeadingLabel, "---°");
    lv_obj_set_style_text_font(ui_CompassHeadingLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassPitchLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassPitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassPitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassPitchLabel, 0);
    lv_obj_set_y(ui_CompassPitchLabel, 21);
    lv_obj_set_align(ui_CompassPitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassPitchLabel, "PITCH: 0°");

    ui_CompassRollLabel = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassRollLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassRollLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassRollLabel, -2);
    lv_obj_set_y(ui_CompassRollLabel, 55);
    lv_obj_set_align(ui_CompassRollLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassRollLabel, "ROLL: 0°");

    ui_CompassBackButton = lv_button_create(ui_CompassScreen);
    lv_obj_set_width(ui_CompassBackButton, 100);
    lv_obj_set_height(ui_CompassBackButton, 36);
    lv_obj_set_x(ui_CompassBackButton, 0);
    lv_obj_set_y(ui_CompassBackButton, -5);
    lv_obj_set_align(ui_CompassBackButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CompassBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassBackButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassBackButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CompassBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompassBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvBackLabel2 = lv_label_create(ui_CompassBackButton);
    lv_obj_set_width(ui_EnvBackLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvBackLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EnvBackLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvBackLabel2, "BACK");

    lv_obj_add_event_cb(ui_CompassBackButton, ui_event_CompassBackButton, LV_EVENT_ALL, NULL);

}

void ui_CompassScreen_screen_destroy(void)
{
    if(ui_CompassScreen) lv_obj_del(ui_CompassScreen);

    // NULL screen variables
    ui_CompassScreen = NULL;
    ui_CompassTitleLabel = NULL;
    ui_CompassStatusLabel = NULL;
    ui_CompassDirectionLabel = NULL;
    ui_CompassHeadingLabel = NULL;
    ui_CompassPitchLabel = NULL;
    ui_CompassRollLabel = NULL;
    ui_CompassBackButton = NULL;
    ui_EnvBackLabel2 = NULL;

}
