// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_EnvScreen = NULL;
lv_obj_t * ui_EnvTitleLabel = NULL;
lv_obj_t * ui_AHTTempLabel = NULL;
lv_obj_t * ui_AHTHumiLabel = NULL;
lv_obj_t * ui_EnvBackButton = NULL;
lv_obj_t * ui_EnvBackLabel = NULL;
lv_obj_t * ui_SPLPressureLabel = NULL;
lv_obj_t * ui_SPLAltitudeLabel = NULL;
// event funtions
void ui_event_EnvBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_EnvScreen_screen_init(void)
{
    ui_EnvScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_EnvScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EnvScreen, lv_color_hex(0xF4F7FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnvScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvTitleLabel = lv_label_create(ui_EnvScreen);
    lv_obj_set_width(ui_EnvTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EnvTitleLabel, 0);
    lv_obj_set_y(ui_EnvTitleLabel, 25);
    lv_obj_set_align(ui_EnvTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_EnvTitleLabel, "ENVIRONMENT");
    lv_obj_set_style_text_color(ui_EnvTitleLabel, lv_color_hex(0x263238), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnvTitleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AHTTempLabel = lv_label_create(ui_EnvScreen);
    lv_obj_set_width(ui_AHTTempLabel, LV_SIZE_CONTENT);   /// 210
    lv_obj_set_height(ui_AHTTempLabel, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_AHTTempLabel, 0);
    lv_obj_set_y(ui_AHTTempLabel, 82);
    lv_obj_set_align(ui_AHTTempLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AHTTempLabel, "TEMP: --.-- C");
    lv_obj_set_style_text_color(ui_AHTTempLabel, lv_color_hex(0xE65100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AHTTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AHTTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AHTTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AHTHumiLabel = lv_label_create(ui_EnvScreen);
    lv_obj_set_width(ui_AHTHumiLabel, LV_SIZE_CONTENT);   /// 210
    lv_obj_set_height(ui_AHTHumiLabel, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_AHTHumiLabel, 0);
    lv_obj_set_y(ui_AHTHumiLabel, 123);
    lv_obj_set_align(ui_AHTHumiLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AHTHumiLabel, "HUM: --.-- %RH");
    lv_obj_set_style_text_color(ui_AHTHumiLabel, lv_color_hex(0x0277BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AHTHumiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AHTHumiLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AHTHumiLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvBackButton = lv_button_create(ui_EnvScreen);
    lv_obj_set_width(ui_EnvBackButton, 100);
    lv_obj_set_height(ui_EnvBackButton, 36);
    lv_obj_set_x(ui_EnvBackButton, 0);
    lv_obj_set_y(ui_EnvBackButton, -10);
    lv_obj_set_align(ui_EnvBackButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_EnvBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_EnvBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EnvBackButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EnvBackButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnvBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EnvBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnvBackLabel = lv_label_create(ui_EnvBackButton);
    lv_obj_set_width(ui_EnvBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnvBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EnvBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnvBackLabel, "BACK");

    ui_SPLPressureLabel = lv_label_create(ui_EnvScreen);
    lv_obj_set_width(ui_SPLPressureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPLPressureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPLPressureLabel, 0);
    lv_obj_set_y(ui_SPLPressureLabel, 164);
    lv_obj_set_align(ui_SPLPressureLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SPLPressureLabel, "PRESS: --.-- hPa");
    lv_obj_set_style_text_color(ui_SPLPressureLabel, lv_color_hex(0x2E7D32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SPLPressureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SPLPressureLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPLAltitudeLabel = lv_label_create(ui_EnvScreen);
    lv_obj_set_width(ui_SPLAltitudeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPLAltitudeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPLAltitudeLabel, 0);
    lv_obj_set_y(ui_SPLAltitudeLabel, 205);
    lv_obj_set_align(ui_SPLAltitudeLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SPLAltitudeLabel, "ALT: --.-- m");
    lv_obj_set_style_text_color(ui_SPLAltitudeLabel, lv_color_hex(0x6A1B9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SPLAltitudeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SPLAltitudeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_EnvBackButton, ui_event_EnvBackButton, LV_EVENT_ALL, NULL);

}

void ui_EnvScreen_screen_destroy(void)
{
    if(ui_EnvScreen) lv_obj_del(ui_EnvScreen);

    // NULL screen variables
    ui_EnvScreen = NULL;
    ui_EnvTitleLabel = NULL;
    ui_AHTTempLabel = NULL;
    ui_AHTHumiLabel = NULL;
    ui_EnvBackButton = NULL;
    ui_EnvBackLabel = NULL;
    ui_SPLPressureLabel = NULL;
    ui_SPLAltitudeLabel = NULL;

}
