// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef UI_ENVSCREEN_H
#define UI_ENVSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EnvScreen
extern void ui_EnvScreen_screen_init(void);
extern void ui_EnvScreen_screen_destroy(void);
extern lv_obj_t * ui_EnvScreen;
extern lv_obj_t * ui_EnvTitleLabel;
extern lv_obj_t * ui_AHTTempLabel;
extern lv_obj_t * ui_AHTHumiLabel;
extern void ui_event_EnvBackButton(lv_event_t * e);
extern lv_obj_t * ui_EnvBackButton;
extern lv_obj_t * ui_EnvBackLabel;
extern lv_obj_t * ui_SPLPressureLabel;
extern lv_obj_t * ui_SPLAltitudeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

