// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_TitleLabel;
extern void ui_event_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_MenuButton;
extern lv_obj_t * ui_MenuLabel;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_BatteryLabel;
extern lv_obj_t * ui_HeartRateLabel;
extern lv_obj_t * ui_StatusIcon;
extern lv_obj_t * ui_DateLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

