// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_TitleLabel = NULL;
lv_obj_t * ui_MenuButton = NULL;
lv_obj_t * ui_MenuLabel = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_BatteryLabel = NULL;
lv_obj_t * ui_HeartRateLabel = NULL;
lv_obj_t * ui_StatusIcon = NULL;
lv_obj_t * ui_DateLabel = NULL;
// event funtions
void ui_event_MenuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x10151C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel, 0);
    lv_obj_set_y(ui_TitleLabel, 20);
    lv_obj_set_align(ui_TitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TitleLabel, "LFC-Watch");
    lv_label_set_recolor(ui_TitleLabel, true);
    lv_obj_set_style_text_color(ui_TitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuButton = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_MenuButton, 160);
    lv_obj_set_height(ui_MenuButton, 44);
    lv_obj_set_x(ui_MenuButton, 0);
    lv_obj_set_y(ui_MenuButton, -20);
    lv_obj_set_align(ui_MenuButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuLabel = lv_label_create(ui_MenuButton);
    lv_obj_set_width(ui_MenuLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuLabel, "MENU");
    lv_obj_set_style_text_color(ui_MenuLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 0);
    lv_obj_set_y(ui_TimeLabel, 45);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TimeLabel, "12:45");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x415AE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabel, -10);
    lv_obj_set_y(ui_BatteryLabel, 12);
    lv_obj_set_align(ui_BatteryLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_BatteryLabel, "80%");
    lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0x81C784), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_HeartRateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateLabel, 0);
    lv_obj_set_y(ui_HeartRateLabel, 35);
    lv_obj_set_align(ui_HeartRateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateLabel, "-- BPM");
    lv_obj_set_style_text_color(ui_HeartRateLabel, lv_color_hex(0xEF9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartRateLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusIcon = lv_image_create(ui_HomeScreen);
    lv_image_set_src(ui_StatusIcon, &ui_img_heart_icon_png);
    lv_obj_set_width(ui_StatusIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_StatusIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_StatusIcon, -68);
    lv_obj_set_y(ui_StatusIcon, 33);
    lv_obj_set_align(ui_StatusIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatusIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_StatusIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, 71);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DateLabel, "2026-08-10");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0x3482F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuButton, ui_event_MenuButton, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_TitleLabel = NULL;
    ui_MenuButton = NULL;
    ui_MenuLabel = NULL;
    ui_TimeLabel = NULL;
    ui_BatteryLabel = NULL;
    ui_HeartRateLabel = NULL;
    ui_StatusIcon = NULL;
    ui_DateLabel = NULL;

}
