// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_MenuTitleLable = NULL;
lv_obj_t * ui_SportButton = NULL;
lv_obj_t * ui_SPORTLabel = NULL;
lv_obj_t * ui_EnvButton = NULL;
lv_obj_t * ui_ENVLabel = NULL;
lv_obj_t * ui_MenuSettingsButton = NULL;
lv_obj_t * ui_MenuSettingsLabel = NULL;
lv_obj_t * ui_CompassButton = NULL;
lv_obj_t * ui_SPORTLabel3 = NULL;
lv_obj_t * ui_MenuBackButton = NULL;
lv_obj_t * ui_MenuBackLabel = NULL;
// event funtions
void ui_event_SportButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SportScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_SportScreen_screen_init);
    }
}

void ui_event_EnvButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_EnvScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_EnvScreen_screen_init);
    }
}

void ui_event_MenuSettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_CompassButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CompassScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_CompassScreen_screen_init);
    }
}

void ui_event_MenuBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen, lv_color_hex(0x10151C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuTitleLable = lv_label_create(ui_MenuScreen);
    lv_obj_set_width(ui_MenuTitleLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuTitleLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuTitleLable, 0);
    lv_obj_set_y(ui_MenuTitleLable, 15);
    lv_obj_set_align(ui_MenuTitleLable, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MenuTitleLable, "MENU");
    lv_obj_set_style_text_color(ui_MenuTitleLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuTitleLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuTitleLable, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_SportButton, 90);
    lv_obj_set_height(ui_SportButton, 55);
    lv_obj_set_x(ui_SportButton, 6);
    lv_obj_set_y(ui_SportButton, 54);
    lv_obj_add_flag(ui_SportButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SportButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SportButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SportButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPORTLabel = lv_label_create(ui_SportButton);
    lv_obj_set_width(ui_SPORTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPORTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SPORTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPORTLabel, "SPORT");

    ui_EnvButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_EnvButton, 90);
    lv_obj_set_height(ui_EnvButton, 55);
    lv_obj_set_x(ui_EnvButton, 137);
    lv_obj_set_y(ui_EnvButton, 54);
    lv_obj_add_flag(ui_EnvButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_EnvButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EnvButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EnvButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnvButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EnvButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnvButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ENVLabel = lv_label_create(ui_EnvButton);
    lv_obj_set_width(ui_ENVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ENVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ENVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ENVLabel, "ENV");

    ui_MenuSettingsButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_MenuSettingsButton, 90);
    lv_obj_set_height(ui_MenuSettingsButton, 55);
    lv_obj_set_x(ui_MenuSettingsButton, 137);
    lv_obj_set_y(ui_MenuSettingsButton, 145);
    lv_obj_add_flag(ui_MenuSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuSettingsButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuSettingsButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MenuSettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuSettingsLabel = lv_label_create(ui_MenuSettingsButton);
    lv_obj_set_width(ui_MenuSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuSettingsLabel, "SETTINGS");

    ui_CompassButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_CompassButton, 90);
    lv_obj_set_height(ui_CompassButton, 55);
    lv_obj_set_x(ui_CompassButton, 6);
    lv_obj_set_y(ui_CompassButton, 145);
    lv_obj_add_flag(ui_CompassButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CompassButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CompassButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompassButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPORTLabel3 = lv_label_create(ui_CompassButton);
    lv_obj_set_width(ui_SPORTLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPORTLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SPORTLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPORTLabel3, "COMPASS");

    ui_MenuBackButton = lv_button_create(ui_MenuScreen);
    lv_obj_set_width(ui_MenuBackButton, 100);
    lv_obj_set_height(ui_MenuBackButton, 36);
    lv_obj_set_x(ui_MenuBackButton, 0);
    lv_obj_set_y(ui_MenuBackButton, -8);
    lv_obj_set_align(ui_MenuBackButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MenuBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MenuBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MenuBackButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuBackButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MenuBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuBackLabel = lv_label_create(ui_MenuBackButton);
    lv_obj_set_width(ui_MenuBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuBackLabel, "BACK");

    lv_obj_add_event_cb(ui_SportButton, ui_event_SportButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnvButton, ui_event_EnvButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuSettingsButton, ui_event_MenuSettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CompassButton, ui_event_CompassButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuBackButton, ui_event_MenuBackButton, LV_EVENT_ALL, NULL);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_MenuTitleLable = NULL;
    ui_SportButton = NULL;
    ui_SPORTLabel = NULL;
    ui_EnvButton = NULL;
    ui_ENVLabel = NULL;
    ui_MenuSettingsButton = NULL;
    ui_MenuSettingsLabel = NULL;
    ui_CompassButton = NULL;
    ui_SPORTLabel3 = NULL;
    ui_MenuBackButton = NULL;
    ui_MenuBackLabel = NULL;

}
