// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_MenuTitleLable;
extern void ui_event_SportButton(lv_event_t * e);
extern lv_obj_t * ui_SportButton;
extern lv_obj_t * ui_SPORTLabel;
extern void ui_event_EnvButton(lv_event_t * e);
extern lv_obj_t * ui_EnvButton;
extern lv_obj_t * ui_ENVLabel;
extern void ui_event_MenuSettingsButton(lv_event_t * e);
extern lv_obj_t * ui_MenuSettingsButton;
extern lv_obj_t * ui_MenuSettingsLabel;
extern void ui_event_CompassButton(lv_event_t * e);
extern lv_obj_t * ui_CompassButton;
extern lv_obj_t * ui_SPORTLabel3;
extern void ui_event_MenuBackButton(lv_event_t * e);
extern lv_obj_t * ui_MenuBackButton;
extern lv_obj_t * ui_MenuBackLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

