// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_SettingsTitleLabel = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackLabel = NULL;
lv_obj_t * ui_BrightnessTitleLabel = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_BrightnessValueLabel = NULL;
lv_obj_t * ui_BLETitleLabel = NULL;
lv_obj_t * ui_BLEPowerSwitch = NULL;
lv_obj_t * ui_BLEStatusLabel = NULL;
// event funtions
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        BLEPowerSwitchSync(e);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_BrightnessValueLabel, target, "", "%");
        BrightnessSliderChanged(e);
    }
}

void ui_event_BLEPowerSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BLEPowerSwitchChanged(e);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x10151C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsTitleLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SettingsTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsTitleLabel, 0);
    lv_obj_set_y(ui_SettingsTitleLabel, 20);
    lv_obj_set_align(ui_SettingsTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SettingsTitleLabel, "设置");
    lv_obj_set_style_text_color(ui_SettingsTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsTitleLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BackButton, 87);
    lv_obj_set_height(ui_BackButton, 30);
    lv_obj_set_x(ui_BackButton, -3);
    lv_obj_set_y(ui_BackButton, -10);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x455A64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "返回");
    lv_obj_set_style_text_color(ui_BackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessTitleLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BrightnessTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessTitleLabel, 0);
    lv_obj_set_y(ui_BrightnessTitleLabel, 65);
    lv_obj_set_align(ui_BrightnessTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_BrightnessTitleLabel, "BRIGHTNESS");
    lv_obj_set_style_text_color(ui_BrightnessTitleLabel, lv_color_hex(0xB0BEC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_SettingsScreen);
    lv_slider_set_value(ui_BrightnessSlider, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_BrightnessSlider, 100,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 180);
    lv_obj_set_height(ui_BrightnessSlider, 16);
    lv_obj_set_x(ui_BrightnessSlider, 2);
    lv_obj_set_y(ui_BrightnessSlider, -36);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x37474F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x2196F3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BrightnessSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BrightnessSlider,
                                                                                                       lv_obj_get_style_pad_right(ui_BrightnessSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BrightnessValueLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BrightnessValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessValueLabel, 0);
    lv_obj_set_y(ui_BrightnessValueLabel, -17);
    lv_obj_set_align(ui_BrightnessValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessValueLabel, "80%");
    lv_obj_set_style_text_color(ui_BrightnessValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLETitleLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BLETitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLETitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLETitleLabel, -5);
    lv_obj_set_y(ui_BLETitleLabel, 142);
    lv_obj_set_align(ui_BLETitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_BLETitleLabel, "BLUETOOTH");
    lv_obj_set_style_text_color(ui_BLETitleLabel, lv_color_hex(0xB0BEC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLETitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEPowerSwitch = lv_switch_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BLEPowerSwitch, 64);
    lv_obj_set_height(ui_BLEPowerSwitch, 32);
    lv_obj_set_x(ui_BLEPowerSwitch, 1);
    lv_obj_set_y(ui_BLEPowerSwitch, 43);
    lv_obj_set_align(ui_BLEPowerSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BLEPowerSwitch, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLEPowerSwitch, lv_color_hex(0x37474F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEPowerSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLEPowerSwitch, lv_color_hex(0x546E7A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BLEPowerSwitch, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_radius(ui_BLEPowerSwitch, 20, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_BLEPowerSwitch, lv_color_hex(0x2196F3), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BLEPowerSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_BLEPowerSwitch, lv_color_hex(0x42A5F5),
                              LV_PART_INDICATOR | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BLEPowerSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED | LV_STATE_PRESSED);

    lv_obj_set_style_radius(ui_BLEPowerSwitch, 999, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLEPowerSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEPowerSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BLEStatusLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BLEStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLEStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLEStatusLabel, 0);
    lv_obj_set_y(ui_BLEStatusLabel, 75);
    lv_obj_set_align(ui_BLEStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLEStatusLabel, "WAITING");
    lv_obj_set_style_text_color(ui_BLEStatusLabel, lv_color_hex(0xFFB74D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLEStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BLEPowerSwitch, ui_event_BLEPowerSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_SettingsTitleLabel = NULL;
    ui_BackButton = NULL;
    ui_BackLabel = NULL;
    ui_BrightnessTitleLabel = NULL;
    ui_BrightnessSlider = NULL;
    ui_BrightnessValueLabel = NULL;
    ui_BLETitleLabel = NULL;
    ui_BLEPowerSwitch = NULL;
    ui_BLEStatusLabel = NULL;

}
