// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef UI_SPORTSCREEN_H
#define UI_SPORTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SportScreen
extern void ui_SportScreen_screen_init(void);
extern void ui_SportScreen_screen_destroy(void);
extern lv_obj_t * ui_SportScreen;
extern lv_obj_t * ui_SportTitleLabel;
extern lv_obj_t * ui_AccelTitleLabel;
extern lv_obj_t * ui_AccelXLabel;
extern lv_obj_t * ui_AccelYLabel;
extern lv_obj_t * ui_AccelZLabel;
extern lv_obj_t * ui_GyroTitleLabel;
extern lv_obj_t * ui_GyroXLabel;
extern lv_obj_t * ui_GyroYLabel;
extern lv_obj_t * ui_GyroZLabel;
extern lv_obj_t * ui_MPUTemperatureLabel;
extern void ui_event_SportBackButton(lv_event_t * e);
extern lv_obj_t * ui_SportBackButton;
extern lv_obj_t * ui_SportBackLabel;
extern lv_obj_t * ui_MPUStepCountLabel;
extern lv_obj_t * ui_MPUWristLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

