// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "../ui.h"

lv_obj_t * ui_SportScreen = NULL;
lv_obj_t * ui_SportTitleLabel = NULL;
lv_obj_t * ui_AccelTitleLabel = NULL;
lv_obj_t * ui_AccelXLabel = NULL;
lv_obj_t * ui_AccelYLabel = NULL;
lv_obj_t * ui_AccelZLabel = NULL;
lv_obj_t * ui_GyroTitleLabel = NULL;
lv_obj_t * ui_GyroXLabel = NULL;
lv_obj_t * ui_GyroYLabel = NULL;
lv_obj_t * ui_GyroZLabel = NULL;
lv_obj_t * ui_MPUTemperatureLabel = NULL;
lv_obj_t * ui_SportBackButton = NULL;
lv_obj_t * ui_SportBackLabel = NULL;
lv_obj_t * ui_MPUStepCountLabel = NULL;
lv_obj_t * ui_MPUWristLabel = NULL;
// event funtions
void ui_event_SportBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_SportScreen_screen_init(void)
{
    ui_SportScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SportScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SportTitleLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_SportTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SportTitleLabel, 0);
    lv_obj_set_y(ui_SportTitleLabel, 14);
    lv_obj_set_align(ui_SportTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SportTitleLabel, "MPU6050");
    lv_obj_set_style_text_font(ui_SportTitleLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccelTitleLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_AccelTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccelTitleLabel, -60);
    lv_obj_set_y(ui_AccelTitleLabel, 58);
    lv_obj_set_align(ui_AccelTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AccelTitleLabel, "ACCEL (mg)");

    ui_AccelXLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_AccelXLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelXLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccelXLabel, -60);
    lv_obj_set_y(ui_AccelXLabel, 86);
    lv_obj_set_align(ui_AccelXLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AccelXLabel, "X: 0 mg");

    ui_AccelYLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_AccelYLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelYLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccelYLabel, -60);
    lv_obj_set_y(ui_AccelYLabel, 114);
    lv_obj_set_align(ui_AccelYLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AccelYLabel, "Y: 0 mg");

    ui_AccelZLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_AccelZLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccelZLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccelZLabel, -60);
    lv_obj_set_y(ui_AccelZLabel, 142);
    lv_obj_set_align(ui_AccelZLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AccelZLabel, "Z: 0 mg");

    ui_GyroTitleLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_GyroTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroTitleLabel, 60);
    lv_obj_set_y(ui_GyroTitleLabel, 58);
    lv_obj_set_align(ui_GyroTitleLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_GyroTitleLabel, "GYRO (dps)");

    ui_GyroXLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_GyroXLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroXLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroXLabel, 60);
    lv_obj_set_y(ui_GyroXLabel, 86);
    lv_obj_set_align(ui_GyroXLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_GyroXLabel, "X: 0.000");

    ui_GyroYLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_GyroYLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroYLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroYLabel, 60);
    lv_obj_set_y(ui_GyroYLabel, 114);
    lv_obj_set_align(ui_GyroYLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_GyroYLabel, "Y: 0.000");

    ui_GyroZLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_GyroZLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GyroZLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GyroZLabel, 60);
    lv_obj_set_y(ui_GyroZLabel, 142);
    lv_obj_set_align(ui_GyroZLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_GyroZLabel, "Z: 0.000");

    ui_MPUTemperatureLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_MPUTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPUTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPUTemperatureLabel, -2);
    lv_obj_set_y(ui_MPUTemperatureLabel, 171);
    lv_obj_set_align(ui_MPUTemperatureLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MPUTemperatureLabel, "EMP: 0.00 C");

    ui_SportBackButton = lv_button_create(ui_SportScreen);
    lv_obj_set_width(ui_SportBackButton, 100);
    lv_obj_set_height(ui_SportBackButton, 36);
    lv_obj_set_x(ui_SportBackButton, 0);
    lv_obj_set_y(ui_SportBackButton, -10);
    lv_obj_set_align(ui_SportBackButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SportBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SportBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SportBackButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SportBackButton, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SportBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SportBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SportBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SportBackLabel = lv_label_create(ui_SportBackButton);
    lv_obj_set_width(ui_SportBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SportBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SportBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SportBackLabel, "BACK");

    ui_MPUStepCountLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_MPUStepCountLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPUStepCountLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPUStepCountLabel, 0);
    lv_obj_set_y(ui_MPUStepCountLabel, 197);
    lv_obj_set_align(ui_MPUStepCountLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MPUStepCountLabel, "STEPS: 0");
    lv_obj_set_style_text_color(ui_MPUStepCountLabel, lv_color_hex(0x2E7D32), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPUStepCountLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPUStepCountLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPUWristLabel = lv_label_create(ui_SportScreen);
    lv_obj_set_width(ui_MPUWristLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPUWristLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPUWristLabel, 0);
    lv_obj_set_y(ui_MPUWristLabel, 39);
    lv_obj_set_align(ui_MPUWristLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MPUWristLabel, "WRIST: DOWN  RAISE: 0");

    lv_obj_add_event_cb(ui_SportBackButton, ui_event_SportBackButton, LV_EVENT_ALL, NULL);

}

void ui_SportScreen_screen_destroy(void)
{
    if(ui_SportScreen) lv_obj_del(ui_SportScreen);

    // NULL screen variables
    ui_SportScreen = NULL;
    ui_SportTitleLabel = NULL;
    ui_AccelTitleLabel = NULL;
    ui_AccelXLabel = NULL;
    ui_AccelYLabel = NULL;
    ui_AccelZLabel = NULL;
    ui_GyroTitleLabel = NULL;
    ui_GyroXLabel = NULL;
    ui_GyroYLabel = NULL;
    ui_GyroZLabel = NULL;
    ui_MPUTemperatureLabel = NULL;
    ui_SportBackButton = NULL;
    ui_SportBackLabel = NULL;
    ui_MPUStepCountLabel = NULL;
    ui_MPUWristLabel = NULL;

}
