// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef _OV_WATCH_SQUARELINE_LEARN_UI_H
#define _OV_WATCH_SQUARELINE_LEARN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_HomeScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_MenuScreen.h"
#include "screens/ui_SportScreen.h"
#include "screens/ui_EnvScreen.h"
#include "screens/ui_CompassScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_heart_icon_png);    // assets/heart_icon.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
