// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#include "ui.h"
#include "app_ui_bridge.h" // SquareLine界面层调用的应用接口

void BrightnessSliderChanged(lv_event_t * e)
{
	lv_obj_t *slider;				//产生本次事件的亮度滑块
	int32_t brightness_percent;		//从滑块读取的0~100亮度百分比

	slider = lv_event_get_target(e); //获取产生本次事件的对象
	if(slider == NULL) return; //防御性编程：如果对象为空，直接返回

	brightness_percent = lv_slider_get_value(slider); //读取滑块数值

	/*确保亮度在0~100范围内*/
	if(brightness_percent < 0) brightness_percent = 0;
	if(brightness_percent > 100) brightness_percent = 100;

	APP_BrightnessChanged((uint8_t)brightness_percent); //把亮度百分比发送给应用层
}

void BLEPowerSwitchChanged(lv_event_t * e)
{
	lv_obj_t *ble_switch;	//产生本次事件的BLE开关
	uint8_t enabled;		//BLE开关的当前状态

	/* 事件没有有效目标对象时无法读取开关状态，不向BLETask发送请求。 */
	ble_switch = lv_event_get_target(e); //获取产生本次事件的对象
	if(ble_switch == NULL) return; //防御性编程：如果对象为空

	/*
	 * Switch打开时带有LV_STATE_CHECKED状态。
	 * lv_obj_has_state()返回非零表示存在该状态。
	*/
	if(lv_obj_has_state(ble_switch, LV_STATE_CHECKED))
	{
		enabled = 1U; //BLE开关打开
	}
	else
	{
		enabled = 0U; //BLE开关关闭
	}

	APP_BLEPowerChanged(enabled); // 将开关状态转换为BLETask电源控制请求
}

/*
 * 设置页面加载时，使用应用层当前状态覆盖SquareLine控件默认值。
 * 模块开启时勾选开关，关闭时取消勾选；随后同步OFF、READY或ACTIVE文字。
 */
void BLEPowerSwitchSync(lv_event_t * e)
{
	(void)e; //未使用参数，避免编译器警告

	if(ui_BLEPowerSwitch == NULL) return; //防御性编程：如果对象为空，直接返回

	if(APP_BLEPowerIsEnabled() != 0U)
	{
		lv_obj_add_state(ui_BLEPowerSwitch, LV_STATE_CHECKED); //BLE开关打开
	}
	else
	{
		lv_obj_remove_state(ui_BLEPowerSwitch, LV_STATE_CHECKED); //BLE开关关闭
	}

	BLEStatusLabelUpdate((uint8_t)APP_BLEGetStatus());
}

/*
 * 根据UiTask传入的状态同步文字与颜色。标签尚未创建时直接返回；
 * 状态值不属于OFF、READY或ACTIVE时显示UNKNOWN，便于发现跨层状态错误。
 */
void BLEStatusLabelUpdate(uint8_t status)
{
	if(ui_BLEStatusLabel == NULL ) return;

	if(status == APP_BLE_STATUS_OFF)
	{
		lv_label_set_text(ui_BLEStatusLabel, "OFF");
		lv_obj_set_style_text_color(ui_BLEStatusLabel, lv_color_hex(0x90A4AE), LV_PART_MAIN);
	}
	else if(status == APP_BLE_STATUS_READY)
	{
		lv_label_set_text(ui_BLEStatusLabel, "READY");
		lv_obj_set_style_text_color(ui_BLEStatusLabel, lv_color_hex(0xFFB74D), LV_PART_MAIN);
	}
	else if(status == APP_BLE_STATUS_ACTIVE)
	{
		lv_label_set_text(ui_BLEStatusLabel, "ACTIVE");
		lv_obj_set_style_text_color(ui_BLEStatusLabel, lv_color_hex(0x66BB6A), LV_PART_MAIN);
	}
	else
	{
		lv_label_set_text(ui_BLEStatusLabel, "UNKNOWN");
		lv_obj_set_style_text_color(ui_BLEStatusLabel, lv_color_hex(0xEF5350), LV_PART_MAIN);
	}
}
