// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: OV_Watch_SquareLine_Learn

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BLEPowerSwitchSync(lv_event_t * e);
void BrightnessSliderChanged(lv_event_t * e);
void BLEPowerSwitchChanged(lv_event_t * e);

void BLEStatusLabelUpdate(uint8_t status);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
